<?php
echo $this->flashMessenger()->render('success', ['alert', 'alert-success']);
?>
<div class="row">
    <?php foreach ($this->products as $index => $product) : ?>
        <?php echo $this->partial('products/index/product-preview.phtml', [
            'product' => $product
        ]); ?>
        <?php if (($index+1)%3 == 0) : ?>
</div>
<div class="row">
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<div class="clearfix">
    <div class="pull-right">
    <?php
    echo $this->paginationControl($this->products,
        'Sliding',
        'application/pagination-control.phtml',
        ['route' => 'products']);
    ?>
    </div>
</div>