<?php
/** @var \Products\Form\Product $form */
$form = $this->form;
?>
<?php echo $this->form()->openTag($form); ?>
    <?php foreach ($form->getElements() as $element) : ?>
    <div class="form-group">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formElement($element); ?>
        <?php echo $this->formElementErrors($element); ?>
    </div>
    <?php endforeach; ?>
    <button type="submit" class="btn btn-default">Save</button>
<?php echo $this->form()->closeTag();