<?php
/** @var \Products\Entity\Product $product */
$product = $this->product;
?>
<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <?php echo $this->escapeHtml($product->getName()) ?>
                <strong class="pull-right">
                    <?php echo $this->currencyFormat($product->getPrice()->getAmount(), 'USD'); ?>
                </strong>
            </h3>
        </div>
        <div class="panel-body">
            <p><?php echo nl2br($this->escapeHtml($product->getShortDescription())); ?></p>
            <p>
                <a class="btn btn-success pull-right"
                   href="<?php echo $this->url('cart/add',
                       ['product' => $product->getId(), 'quantity' => 1]) ?>"
                   target="_blank">Add to cart &raquo;</a>
            </p>
        </div>
    </div>
</div>