<?php
/** @var \Orders\Entity\Order[] $orders */
$orders = $this->orders;
?>
<h1>List of orders</h1>
<table class="table table-condensed">
    <thead>
        <tr>
            <th>Date purchased</th>
            <th>Number of products</th>
            <th>Price</th>
            <th>Customer</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($orders as $order) : ?>
        <tr>
            <td><?php echo $order->getOrderDate()->format('d/m/Y H:i'); ?></td>
            <td><?php echo count($order->getOrderItems()->getIterator()); ?></td>
            <td><?php echo $this->currencyFormat($order->getTotalPrice()->getAmount(),
                    'USD', null, 'en_US'); ?></td>
            <td><?php echo $order->getShippingDetails()->getFirstName() ?>
                <?php echo $order->getShippingDetails()->getLastName() ?>
            </td>
            <td><a href="<?php echo $this->url('order/view', ['id' => $order->getId()]); ?>"
                    class="btn btn-default">
                    View
            </a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>