<?php
echo $this->flashMessenger()->render('success', ['alert', 'alert-success']);
/** @var \Orders\Entity\Order $order */
$order = $this->order;
?>
<h1>Order #<?php echo $order->getId(); ?></h1>
<hr>
<h2>Items summary</h2>
<table class="table table-condensed">
    <thead>
    <tr>
        <th width="70%">Product</th>
        <th width="5%">Quantity</th>
        <th>Price</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($order->getOrderItems() as $item) : ?>
        <tr>
            <td>
                <a href="<?php echo $this->url('products/view', ['id' => $item->getProduct()->getId()]); ?>">
                    <?php echo $this->escapeHtml($item->getProduct()->getName()); ?>
                </a>
            </td>
            <td>
                <?php echo $item->getQuantityRequested(); ?>
            </td>
            <td>
                <small>
                    x
                    <?php echo $this->currencyFormat(
                        $item->getProduct()->getPrice()->getAmount(), 'USD', null, 'en_US') ?>
                </small>
            </td>
            <td>
                =
                <?php echo $this->currencyFormat(
                    $item->getQuantifiedPrice()->getAmount(), 'USD', null, 'en_US'); ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="2">
        </td>
        <td colspan="2">
            <strong>Total payed price*: <?php
                echo $this->currencyFormat($order->getTotalPrice()->getAmount(), 'USD', null, 'en_US'); ?>
            </strong>
        </td>
    </tr>
    </tfoot>
</table>
<blockquote>
    * maybe subject to a discount
</blockquote>
<h2>Shipping details</h2>
<?php
$shippingDetails = $order->getShippingDetails();
?>
<table class="table table-bordered table-condensed">
    <tr>
        <th>Customer name</th>
        <td><?php echo $shippingDetails->getFirstName() . ' ' . $shippingDetails->getLastName() ?></td>
    </tr>
    <tr>
        <th>Address</th>
        <td><?php echo $shippingDetails->getAddress() . ', ' . $shippingDetails->getCity() . ', '
                . $shippingDetails->getCountry(); ?></td>
    </tr>
    <tr>
        <th>Phone</th>
        <td><?php echo $shippingDetails->getPhone(); ?></td>
    </tr>
</table>