<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to the best %sSaxophone Shop!%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo $this->translate('Browse the best vintage saxophones!'); ?></p>
</div>

<div class="row">

    <?php foreach ($this->products as $product) : ?>
            <?php echo $this->partial('products/index/product-preview.phtml', [
                'product' => $product
            ]); ?>
    <?php endforeach; ?>
    <a href="<?php echo $this->url('products'); ?>">Show all</a>
</div>
